### ISSUE TITLE
requestReview doesn't work on IOS 

### ISSUE THREAD

**Issue by sukonin** [britannio/in_app_review#10]
`requestReview` doesn't work on IOS after released in TestFlight, but version run locally on physical device works fine and show pop-up with stars.

**Comment by britannio** [comment]
This is the intended behaviour as per https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview#discussion

**Comment by sukonin** [comment]
Thank you!

**Comment by britannio** [comment]
I've made the readme clearer too! https://github.com/britannio/in_app_review/commit/8362bb1e1caa8f68ba7048c3ac1e59599ab39417
