### ISSUE TITLE
AGP 8 build fails without proper namespace

### ISSUE THREAD

**Issue by 127** [britannio/in_app_review#101]
To support AGP 8 namespace is needed or the build fails

* What went wrong:
A problem occurred configuring project ':in_app_review'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by britannio** [comment]
Hey, I merged a fix recently and it'll be released soon.

**Comment by 127** [comment]
Cool!
