### ISSUE TITLE
Kotlin Version Incompatibility Issue

### ISSUE THREAD

**Issue by viralkachhadiya** [britannio/in_app_review#102]
project ':in_app_review' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10

**Comment by britannio** [comment]
Hey, thanks for filing an issue, could you provide some more context please?

**Comment by simonNEON** [comment]
Im facing the same issues since we updated our project kotlin version to 1.7.10 because of other flutter upgrades. It looks like in_app_review is still on 1.6.10. Are there updates planned in the near future? We would really need that upgrade.

**Comment by britannio** [comment]
I just released 2.0.8 which should resolve this!
