### ISSUE TITLE
Deprecation warning in version 2.0.8

### ISSUE THREAD

**Issue by under3415** [britannio/in_app_review#103]
Hi
After upgrading to `in_app_review` `2.0.8` I'm getting this warning:
```
\pub.dev\in_app_review-2.0.8\android\src\main\java\dev\britannio\in_app_review\InAppReviewPlugin.java:185: 
warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
            context.getPackageManager().getPackageInfo("com.android.vending", 0);
                                       ^
```

**Comment by lucaesposto** [comment]
in_app_review 2.0.8

Deprecation warning on `flutter build appbundle`

Note: C:\Users\[my_username]\AppData\Local\Pub\Cache\hosted\pub.dev\in_app_review-2.0.8\android\src\main\java\dev\britannio\in_app_review\InAppReviewPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
