### ISSUE TITLE
iOS in-app ratings & review disabled

### ISSUE THREAD

**Issue by pierrecorbay** [britannio/in_app_review#104]
Hello,

I would like to know what's the current behaviour of `isAvailable()` and `requestReview()` when the user has disabled in-app ratings & reviews in App Store settings ?

![IMG_E3BA8C4C468F-1](https://github.com/britannio/in_app_review/assets/59781996/633a64fa-d4dd-4cc0-9a84-4e395f52683f)

`isAvailable()` returns True (higher than iOS 10.3) and then `requestReview()` shows nothing ?

Would it be possible to implement this: if in-app ratings & reviews setting is disabled then `isAvailable()` returns False ? 
Or a new method like `isRatingDisabled()` that returns True/False depending on whether or not the setting is disabled ?

**Comment by britannio** [comment]
> Would it be possible to implement this: if in-app ratings & reviews setting is disabled then isAvailable() returns False ?

I don't think that there is a way to check the status of this setting unfortunately.

**Comment by pierrecorbay** [comment]
Oh ok :(
