### ISSUE TITLE
Popup not opening

### ISSUE THREAD

**Issue by erperejildo** [britannio/in_app_review#105]
I'm testing on Android emulator and real phone. The app is already published in Google Play.

code:
```
onTap: () async {
                final InAppReview inAppReview = InAppReview.instance;
                if (await inAppReview.isAvailable()) {
                  inAppReview.requestReview();
                }
              },
```

logs:
```
I/InAppReviewPlugin(12698): onMethodCall: isAvailable
I/InAppReviewPlugin(12698): isAvailable: called
I/InAppReviewPlugin(12698): noContextOrActivity: called
I/InAppReviewPlugin(12698): isAvailable: playStoreAndPlayServicesAvailable: true
I/InAppReviewPlugin(12698): isAvailable: lollipopOrLater: true
I/InAppReviewPlugin(12698): isAvailable: Play Store, Play Services and Android version requirements met
I/InAppReviewPlugin(12698): cacheReviewInfo: called
I/InAppReviewPlugin(12698): noContextOrActivity: called
I/PlayCore(12698): UID: [10147]  PID: [12698] ReviewService : requestInAppReview (com.drodriguez.time_tap)
I/InAppReviewPlugin(12698): cacheReviewInfo: Requesting review flow
I/PlayCore(12698): UID: [10147]  PID: [12698] ReviewService : Initiate binding to the service.
```

Documentation:

> Android
> Opens In App Review but only if Play Services are installed on the device and the App is downloaded through the Play Store. Check out the [official documentation](https://developer.android.com/guide/playcore/in-app-review).

**Comment by britannio** [comment]
Hey, did you install the app via the play store to test this?

**Comment by erperejildo** [comment]
> Hey, did you install the app via the play store to test this?

No, I have it published (https://play.google.com/store/apps/details?id=com.drodriguez.time_tap) but I'm testing locally. You mean I need to deploy this wihtout testing it and try directly from production app? Because if so, I don't find it safe TBH. I could try anyway, I don't have any users, but I won't be able to test it locally at all?

**Comment by erperejildo** [comment]
I just tried with the Google Play version (you can test it yourself from that link above) and it doesn't work

**Comment by britannio** [comment]
![image](https://github.com/britannio/in_app_review/assets/33752528/f0563c21-745f-41e7-bb46-17e9bf52036b)
Works for me. Also, I would suggest that you follow the guidelines (https://pub.dev/packages/in_app_review#guidelines) and use `openStoreListing()` when the "Write a review" button is pressed.

**Comment by erperejildo** [comment]
> openStoreListing

for me doesn't work at all. 

How do I detect if didn't open to redirect the user to Google Play with that? Or you mean replacing what I have completely?

**Comment by britannio** [comment]
> > openStoreListing
> 
> For me, it doesn't work at all.
> 
> How do I detect if the user didn't open to redirect them to Google Play with that? Or do you mean replacing what I have completely? Because if so, I could simply open a link

> Or do you mean replacing what I have completely?


Yes, and using a link is completely fine if you wish. The format can be found at https://github.com/britannio/in_app_review/blob/master/in_app_review/android/src/main/java/dev/britannio/in_app_review/InAppReviewPlugin.java#L209

**Comment by erperejildo** [comment]
I'll use that. Feel free to close or not the issue

**Comment by britannio** [comment]
Cool
