### ISSUE TITLE
pub.dev listing doesn't have link back to this sourcce

### ISSUE THREAD

**Issue by MattyBoy4444** [britannio/in_app_review#109]
It wasn't hard to find the source, but it would be great to have the pub.dev listing link back here.

https://pub.dev/packages/in_app_review

Thanks

**Comment by Letalus** [comment]
I agree with @MattyBoy4444 this should be added to the pub.dev listing. This is only adding a link to the project and shouldnt be to time consuming :)

**Comment by britannio** [comment]
Done
