### ISSUE TITLE
Review fails to work in iOS 14 in production

### ISSUE THREAD

**Issue by 127** [britannio/in_app_review#11]
The same app review button works perfectly in lower iOS versions.

**Comment by timmae219** [comment]
The openStoreListing() method does also not work in iOS 14. When the page should be opened, Safari shows a warning that the page could not be opened because the URL is invalid. But if I build the URL which is generated in the method "by hand" and launch it in the browser, it navigates correctly to the store page. Maybe there is a problem with the queryParameters?

**Comment by timmae219** [comment]
Okay, there might not be problems with the queryParameters...

Pressing the Launch Button produces the following stack trace : 

> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(Error, Error while launching https://apps.apple.com/app/id<OUR_APP_ID>?action=write-review, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      MethodChannelUrlLauncher.launch (package:url_launcher_platform_interface/method_channel_url_launcher.dart:40:21)
#4      launch (package:url_launcher/url_launcher.dart:92:58)
#5      InAppReview._launchUrl (package:in_app_review/in_app_review.dart:76:13)
<asynchronous suspension>
#6      InAppReview.openStoreListing (package:in_app_review/in_app_review.dart:60:13)

**Comment by britannio** [comment]
@127 & @timmae219 Can you try running the example app included in the repo on IOS 14. I'm not encountering any of these issues.

**Comment by 127** [comment]
> @127 & @timmae219 Can you try running the example app included in the repo on IOS 14. I'm not encountering any of these issues.

It works as a charm in debug environment even on iOS 14 and in iOS <13 in production.
I've switched from app_review package because of the same issue. Looks like there are some common issues for both packages in iOS 14.

**Comment by britannio** [comment]
@127 Maybe this isn't an IOS 14 issue then but instead, you've exceeded the quota of the IOS review API. You can only use it 3 times in a 365 day period according to https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/ratings-and-reviews/. There's likely also a limit on how frequently you can use the API.

**Comment by 127** [comment]
@britannio I've got my app rejected by app store with another package app_review. It passed with yours (I think they just did not test that this time) but behavior is the same - fails. Installed it on a new device with another appstore account - the same. Not working.

**Comment by britannio** [comment]
> @britannio I've got my app rejected by app store with another package app_review. It passed with yours (I think they just did not test that this time) but behavior is the same - fails. Installed it on a new device with another appstore account - the same. Not working. Ios 13 works.

`app_review` uses the same underlying IOS API. What message did the Apple review team provide when it failed with `app_review`? And did you test IOS 14 before testing IOS 13 to rule out the quota limit? This plugin is very simple so there isn't much that can go wrong on my behalf, especially since it works when you're debugging the app.

**Comment by 127** [comment]
> `app_review` uses the same underlying IOS API. What message did the Apple review team provide when it failed with `app_review`? And did you test IOS 14 before testing IOS 13 to rule out the quota limit? This plugin is very simple so there isn't much that can go wrong on my behalf, especially since it works when you're debugging the app.

Team told me that nothing happens when tapping on review button. I tested it on absolutely new untested device with another test account — 13 worked, 14 — no. I know about 3/365 limit. And there was no any change of code that works with plugin, only iOS version rise. I think both plugins have the same problem.

**Comment by britannio** [comment]
@127 Are you following [the guidelines](https://github.com/britannio/in_app_review#guidelines) as your app might have been rejected for violating them? I just tried out well-spoken.app on an Iphone running IOS 14.1 as it's [using this plugin](https://github.com/britannio/in_app_review/issues/5#issuecomment-682533906) and it worked flawlessly so if @chris-rutkowski could confirm that they are still using `inAppReview.requestReview()` to display the review pop up then IOS 14 can be ruled out as the cause of this.

**Comment by chris-rutkowski** [comment]
@britannio yes we do

**Comment by timmae219** [comment]
@britannio I don't think it has something to do with the quotas. The in-app review dialogue works perfectly in iOS and Android. The problem occurs only if I want to navigate to the store page, if the in-app dialogue is not available. If I understood the concept of the quotas correctly, it handles only the availability of the in-app dialog, doesn't it? Then the quota should not have an effect on launching the store page. Now I'll try to run the example app you told me.

**Comment by britannio** [comment]
> @britannio I don't think it has something to do with the quotas. The in-app review dialogue works perfectly in iOS and Android. The problem occurs only if I want to navigate to the store page, if the in-app dialogue is not available. If I understood the concept of the quotas correctly, it handles only the availability of the in-app dialog, doesn't it? Then the quota should not have an effect on launching the store page. Now I'll try to run the example app you told me.

Are you only having issues with `openStoreListing()`?

**Comment by timmae219** [comment]
@britannio Unfortunately, the example app produces the same stacktrace as my app, no matter which app store id I provide. I think there is a problem with safari on the emulator. If I try to launch the url in the safari app, there also appears an error message which says that the URL is invalid. But the URL works perfectly with my MacOS Safari.

**Comment by timmae219** [comment]
> > @britannio I don't think it has something to do with the quotas. The in-app review dialogue works perfectly in iOS and Android. The problem occurs only if I want to navigate to the store page, if the in-app dialogue is not available. If I understood the concept of the quotas correctly, it handles only the availability of the in-app dialog, doesn't it? Then the quota should not have an effect on launching the store page. Now I'll try to run the example app you told me.
> 
> Are you only having issues with `openStoreListing()`?

Yes. The in-app review works perfectly. I only have issues with the `openStoreListing()`function.

**Comment by britannio** [comment]
> @britannio Unfortunately, the example app produces the same stacktrace as my app, no matter which app store id I provide. I think there is a problem with safari on the emulator. If I try to launch the url in the safari app, there also appears an error message which says that the URL is invalid. But the URL works perfectly with my MacOS Safari.

The simulator doesn't have the App Store installed which would explain `openStoreListing()` not working on the simulator.

**Comment by timmae219** [comment]
> > @britannio Unfortunately, the example app produces the same stacktrace as my app, no matter which app store id I provide. I think there is a problem with safari on the emulator. If I try to launch the url in the safari app, there also appears an error message which says that the URL is invalid. But the URL works perfectly with my MacOS Safari.
> 
> The simulator doesn't have the App Store installed which would explain `openStoreListing()` not working on the simulator.

Well, that makes sense :D I will try it out with a physical device. Then it should work. Thank you for your reply.

**Comment by timmae219** [comment]
@britannio works perfectly on a physical device!

**Comment by 127** [comment]
mine is https://brevy.app
the reject was because it does nothing
![2020-10-23 17 11 51](https://user-images.githubusercontent.com/1647723/97014368-e5182b00-1552-11eb-9e3e-3b2dfe2b5fa3.jpg)

**Comment by britannio** [comment]
@127 I believe that you aren't following [Apple's guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/ratings-and-reviews/), specifically:

> Don't use buttons or other controls to request feedback. Since the system limits how often rating prompts occur, attempting to request feedback in response to a control may result in no rating prompt being displayed.

You should instead use `openStoreListing(...)` to prevent your app from being rejected.

![RPReplay-Final1603468885](https://user-images.githubusercontent.com/33752528/97027407-979bbe00-1552-11eb-87e8-87cfc373ebd6.gif)
^^ Tested on an Iphone 8 running IOS IOS 14.1

**Comment by 127** [comment]
Aaah! Understood! My fault. The issue can be closed
