### ISSUE TITLE
How to track if the review prompt has been shown or not?

### ISSUE THREAD

**Issue by ShivMSense** [britannio/in_app_review#110]
As the `requestReview()` method has a return type `Future<void>`, is there any way I can know if the App store/ Play store prompt has been shown or not?
Alternatively, does the method throw any Platform exception or some other exception in case the prompt doesn't open which I can handle in the code to achieve my purpose?

**Comment by QuinAiton** [comment]
Any response on this?

**Comment by britannio** [comment]
It is not possible because this information is not provided by the underlying API used by this package.
