### ISSUE TITLE
InAppReviewPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by AmineMessabhia** [britannio/in_app_review#113]
Hello,

So your package was -and still is- working fine, but I faced this while building:

`Note: C:\Users\Amine\AppData\Local\Pub\Cache\hosted\pub.dev\in_app_review-2.0.8\android\src\main\java\dev\britannio\in_app_review\InAppReviewPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

I thought you might want to hear about this, and maybe fix it or something, it ain't critical now, but it might become so in the future.

Thank you for the package and for your hard work!

**Comment by Joldersman** [comment]
Confirm. The same problem.

Note: /hosted/pub.dev/in_app_review-2.0.8/android/src/main/java/dev/britannio/in_app_review/InAppReviewPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:19: error: cannot find symbol
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.device_info.DeviceInfoPlusPlugin());
                                                                              ^
  symbol:   class DeviceInfoPlusPlugin
  location: package dev.fluttercommunity.plus.device_info
  
  android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:49: error: cannot find symbol
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin());
                                                                              ^
  symbol:   class PackageInfoPlugin
  location: package dev.fluttercommunity.plus.packageinfo
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by AmineMessabhia** [comment]
@britannio check this whenever possible, please ^_^

**Comment by Wendler** [comment]
@AmineMessabhia Check if #112 solves the problem

**Comment by britannio** [comment]
2.0.9 has been published, thanks for your patience.
