### ISSUE TITLE
Unable to Submit the Star Rating Response 

### ISSUE THREAD

**Issue by kalyanchandra48** [britannio/in_app_review#115]
![IMG_1201_cleanup](https://github.com/britannio/in_app_review/assets/81020495/96c32e8f-17d8-4190-ace0-06d5b0f7d865)

Submit Button is disabled. Not able to Submit the Rating.

**Comment by icesousa** [comment]
Real reviews can only be created when requestReview() is used from the production track. The submit button is disabled on other tracks and in internal app sharing to emphasize this.

read carefully the testing documentation.

**Comment by britannio** [comment]
> Can someone provide the URL for the testing documentation? I encountered the same issue mentioned above.

https://pub.dev/packages/in_app_review#testing-read-carefully
