### ISSUE TITLE
No privacy file found for Apple new directive

### ISSUE THREAD

**Issue by NelfDesign** [britannio/in_app_review#116]

**Comment by britannio** [comment]
Hey, could you clarify this?

**Comment by NelfDesign** [comment]
HI,
According to this article https://developer.apple.com/support/third-party-SDK-requirements/ you have to put a file to add privacy to your package.
If you don't collect data for user, you have to put an empty file.
You may put it in ios=>Resources=> PrivacyInfo.xcprivacy
It's like this

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
</dict>
</plist>
`

**Comment by mvn-hangtran-dn** [comment]
@NelfDesign Sorry, but do you have any document about plugins need to put an empty file when they don't collect data?

**Comment by oremlawi** [comment]
This is the very basic `PrivacyInfo.xcprivacy`:


```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
</dict>
</plist>
```

@britannio this is important to avoid AppStore rejection starting 1 May 2024.

**Comment by mihiro-zenplace** [comment]
@britannio 
Hi. Thank you for creating a great package!

The packages listed at https://developer.apple.com/support/third-party-SDK-requirements/ are examples, and it is likely that packages not listed may also need to be supported.

For example, the package flutter_native_splash is not listed in the above article but is supported.

Reference: 
- https://github.com/jonbhanson/flutter_native_splash/pull/668
- https://github.com/flutter/flutter/issues/139761#issuecomment-1881394943

**Comment by oremlawi** [comment]
Any news about this issue @britannio ?
