### ISSUE TITLE
Request review opened once, didn't open anymore

### ISSUE THREAD

**Issue by nzxcvbnm** [britannio/in_app_review#117]
While testing (debug, android) I did openStoreListing - it worked. Then executed requestReview - it worked and I was super happy, but it showed only once, after pressing the only thing changing were logs in console:

`I/ViewRootImpl@35a208c[MainActivity](23006): ViewPostIme pointer 0
I/ViewRootImpl@35a208c[MainActivity](23006): ViewPostIme pointer 1
I/InAppReviewPlugin(23006): onMethodCall: requestReview
I/InAppReviewPlugin(23006): requestReview: called
I/InAppReviewPlugin(23006): noContextOrActivity: called
I/PlayCore(23006): UID: [10463]  PID: [23006] ReviewService : requestInAppReview (com.canvas.graph)
I/InAppReviewPlugin(23006): requestReview: Requesting review flow
I/PlayCore(23006): UID: [10463]  PID: [23006] ReviewService : Initiate binding to the service.
I/PlayCore(23006): UID: [10463]  PID: [23006] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore(23006): UID: [10463]  PID: [23006] ReviewService : linkToDeath
I/PlayCore(23006): UID: [10463]  PID: [23006] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/PlayCore(23006): UID: [10463]  PID: [23006] ReviewService : Unbind from service.
I/InAppReviewPlugin(23006): onComplete: Successfully requested review flow
I/InAppReviewPlugin(23006): launchReviewFlow: called
I/InAppReviewPlugin(23006): noContextOrActivity: called`

**Comment by britannio** [comment]
> So I have read this: [https://developer.android.com/guide/playcore/in-app-review#quotas](url)
> 
> Is there a possibility to check if quotas for requesting review was exceeded? Or that requestReview() didn't launch?

Unfortunately not. Don't assume it will work more than once in production and you'll be fine.
