### ISSUE TITLE
Feature request: Please make the requestReview a boolean

### ISSUE THREAD

**Issue by dishankjindal1** [britannio/in_app_review#119]
I have a scenario in android, When i call the api requestReview it opens the prompt once, and it doesnt open when user has already given the rating.

I want to capture that response, 
if the function returns TRUE - it means android system prompt appears
if the function return FALSE - It means android system prompt doesnt appear, i want to catch this and open store listing as a fallback.

**Comment by britannio** [comment]
Unfortunately the underlying APIs do not provide such information by design.
