### ISSUE TITLE
await requestReview() cannot wait

### ISSUE THREAD

**Issue by SheepYang1993** [britannio/in_app_review#121]
```
final InAppReview inAppReview = InAppReview.instance;
if (Platform.isIOS) {
    if (await inAppReview.isAvailable()) {
        await inAppReview.requestReview();
        showCustomDialog(); // I hope to display a custom dialog after the system's review pop-up closes
    }
}
```
But the actual effect is that after the system's review pop-up appears, it directly displays the custom dialog.

**Comment by britannio** [comment]
Unfortunately, the underlying APIs do not indicate when the dialog is closed.

**Comment by SheepYang1993** [comment]
> Unfortunately, the underlying APIs do not indicate when the dialog is closed.

Thank you for your reply.
I see that competitor apps can achieve this effect, so I will continue to research and see if there are any other ways to achieve it myself

**Comment by PBomermustekiin** [comment]
any update ? @SheepYang1993
