### ISSUE TITLE
Popup showing up while testing but not since release (production)

### ISSUE THREAD

**Issue by ea-jobvalley** [britannio/in_app_review#122]
Hello,
we integrated this plugin into our app to request user ratings on some conditions. It worked great while implementing, but now that we can test the release build after Apple review it doesn't work anymore when we try it after downloading via Testflight.
When I run the exact build on my iPhone manually it works.
Tried on several devices with different users.

**Comment by britannio** [comment]
https://pub.dev/packages/in_app_review#testing-read-carefully

TestFlight isn't supported.

**Comment by ea-jobvalley** [comment]
> https://pub.dev/packages/in_app_review#testing-read-carefully
> 
> TestFlight isn't supported.

Oh, right. So if I release it should work as intended?
