### ISSUE TITLE
Update your Play Core Maven dependency to an Android 14 compatible version

### ISSUE THREAD

**Issue by palicka** [britannio/in_app_review#125]
HI, I just got an email from Google play console saying:

> Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration
> 
> You may not be able to release future versions of your app with this SDK version to production or open testing.

Could you please have a look at this issue ?
Thank you

**Comment by jcowley** [comment]
@palicka Upgrade to version 2.0.6 of `in_app_review` (or newer). This issue was fixed:
https://github.com/britannio/in_app_review/commit/d1c8802887e8e4c9b63fdb7abaeb2d431a63595a
