### ISSUE TITLE
Update Play Core Maven dependency to an Android 14 compatible version

### ISSUE THREAD

**Issue by faaqi** [britannio/in_app_review#126]
We received this mail from Google regarding the Play Core library issue and as we're not using the Core library in our project , we found that it is being used as transitive dependency from this In app review package.

> com.google.android.play:core has added this note for core:1.10.3:
> 
> Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration
> 
> You may not be able to release future versions of your app with this SDK version to production or open testing.

When will be the next update of this package to resolve this issue?

Here are logs:

<img width="882" alt="image" src="https://github.com/britannio/in_app_review/assets/61233208/43a838ab-15c0-49d4-8e1c-49c943af20dd">

**Comment by britannio** [comment]
Looks similar to https://github.com/britannio/in_app_review/issues/125 which was fixed two years ago.

**Comment by britannio** [comment]
Which version of the package are you using?

**Comment by faaqi** [comment]
We're using 2.0.4. Thanks, I'll update the package

**Comment by craigomac** [comment]
This doesn't appear to be fixed. 

By running `./gradlew app:dependencies > dependencies.txt` and checking `dependencies.txt`:

```
+--- project :in_app_review
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10 (*)
|    +--- com.google.android.play:review:2.0.1
|    |    +--- com.google.android.gms:play-services-basement:18.1.0 (*)
|    |    +--- com.google.android.gms:play-services-tasks:18.0.2 (*)
|    |    \--- com.google.android.play:core-common:2.0.2

```

**Comment by craigomac** [comment]
> ```
> |    |    \--- com.google.android.play:core-common:2.0.2
> ```

Ah, perhaps I misunderstood. `core-common` is one of the split libraries, not the previous monolithic `core` library?

**Comment by britannio** [comment]
The latest version of the API is https://developer.android.com/reference/com/google/android/play/core/release-notes-in_app_reviews which this package is using.

**Comment by manali-sahu** [comment]
Is the issue fixed after upgrading the package?

> We're using 2.0.4. Thanks, I'll update the package

**Comment by faaqi** [comment]
yes @manali-sahu

**Comment by MrLightful** [comment]
```
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':in_app_review:generateReleaseRFile'.
[        ] > Could not resolve all files for configuration ':in_app_review:releaseCompileClasspath'.
[        ]    > Could not find com.google.android.play:items:2.0.1.
[        ]      Required by:
[        ]          project :in_app_review
```

Started getting this on in_app_review v2.0.9.

**Comment by britannio** [comment]
Closing as I don't believe that the issue was with this plugin.
