### ISSUE TITLE
User already rated

### ISSUE THREAD

**Issue by DorraY** [britannio/in_app_review#128]
Good morning,

There is only one information that I could not find anywhere, if the user already submitted the rating, will the pop-up appear to them again? Of course in case they did not exhaust the quota.

Thank you for the amazing package!

**Comment by JadyMcIntyre** [comment]
Any feedback?

**Comment by DorraY** [comment]
@JadyMcIntyre  I searched in the documentations for iOS and Android and I found the answer.

**for Apple**
https://developer.apple.com/design/human-interface-guidelines/ratings-and-reviews

> When you identify places in your experience where it makes sense to ask for feedback, the system checks for previous feedback and — if there isn’t any — displays an in-app prompt that asks for a rating and an optional written review.

for Android
https://developer.android.com/guide/playcore/in-app-review/test

> The user account does not currently have a review for the app.


I hope this helps.

**Comment by JadyMcIntyre** [comment]
@DorraY This definitely does help thank you 🙏 

do you by any chance know if the _inAppReview.isAvailable(); method checks if they have already reviewed, such as you have explained above:

"When you identify places in your experience where it makes sense to ask for feedback, the system checks for previous feedback and — if there isn’t any — displays an in-app prompt that asks for a rating and an optional written review."

**Comment by DorraY** [comment]
@JadyMcIntyre I have no idea about that, makes sense that it does.

**Comment by britannio** [comment]
> do you by any chance know if the _inAppReview.isAvailable(); method checks if they have already reviewed, such as you have explained above:

Sadly not due to the implementation of the underlying APIs.

**Comment by MuddasirAlgoace** [comment]
@britannio @DorraY What happens if the user has already submitted a rating? Will the pop-up appear again? How does the package handle this situation if the user has already submitted their review? From a user experience perspective, if the review has already been submitted, we should display a message saying "Your review has already been submitted." Does the package account for this scenario?

**Comment by DorraY** [comment]
from what I know it will not prompt the user for a review if they already rated, maybe the author can confirm this.
