### ISSUE TITLE
Is there a way to get review value from 1-5 range?

### ISSUE THREAD

**Issue by 127** [britannio/in_app_review#13]
subj

**Comment by britannio** [comment]
Unfortunately not as the API's provided by Apple and Google provide very little information when the review dialog is shown.
See: 
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview
https://developer.android.com/guide/playcore/in-app-review/kotlin-java#launch-review-flow

**Comment by 127** [comment]
very sad )

**Comment by FisherWL** [comment]
this is a stackoverflow question, with the help of sharedpreferences and a counter, it can be done.

**Comment by britannio** [comment]
> this is a stackoverflow question, with the help of sharedpreferences and a counter, it can be done.

@FisherWL Feel free to share the StackOverflow link however I don't see how SharedPreferences can be used to determine what rating a user entered in the review pop up that this plugin displays. 

The plugin asks the underlying OS to display the review pop up, it's not done in Flutter so without an API provided by the underlying OS, there isn't an official way to get the rating provided by the user.

**Comment by FisherWL** [comment]
I misunderstood the question, I thought it meant to prompt 1-5 times.
