### ISSUE TITLE
SKStoreReviewController is deprecated in iOS

### ISSUE THREAD

**Issue by AshokKakunuri** [britannio/in_app_review#130]
Hi,

The underlying SKStoreReviewController class for the rating prompt in iOS is deprecated. Developer documentation states to use RequestReviewAction for the same. 

Is there a plan for upgrading this package to use the latest class instead of the deprecated one.

If there is one, RequestReviewAction has a minimum iOS version of 16.0 and would like to know if you would make code changes to support the earlier versions with the SKStoreReviewController and later than iOS 16.0 with the RequestReviewAction class.

**Comment by britannio** [comment]
Thanks for surfacing this, it's the second time they've deprecated such a simple API :(.
The package will still work on iOS 10.3 upwards after adding the new API, no need to worry.

It's not clear that it still supports Objective-C directly so it'll take more time to support it.

**Comment by thelordzeus** [comment]
any update on when this code will be migrated to the updated RequestReviewAction?

**Comment by amosvizer** [comment]
Anyone knows if this dependency is still supported? Is it worth installing as it seems to not be updated to support the new apple API

**Comment by britannio** [comment]
> Anyone knows if this dependency is still supported? Is it worth installing as it seems to not be updated to support the new apple API

always supported 😎
