### ISSUE TITLE
Cannot parse result path string

### ISSUE THREAD

**Issue by rafidgotit** [britannio/in_app_review#133]
I get the following error only when I try to build in release mode, debug mode just works fine.
```
* What went wrong:
Execution failed for task ':in_app_review:verifyReleaseResources'.
> A build operation failed.
      Cannot parse result path string:                                
   > Cannot parse result path string:                                
```
For more information, this is the output of my `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4037],
    locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio  
      installer for the "Desktop development with C++" workload, and include these    
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest    
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```
Kindly look into this issue...
Thanks in advance!

**Comment by britannio** [comment]
> I get the following error only when I try to build in release mode, debug mode just works fine.
> 
> ```
> * What went wrong:
> Execution failed for task ':in_app_review:verifyReleaseResources'.
> > A build operation failed.
>       Cannot parse result path string:                                
>    > Cannot parse result path string:                                
> ```
> 
> For more information, this is the output of my `flutter doctor`
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4037],
>     locale en-US)
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> [√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
> [√] Chrome - develop for the web
> [!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0)
>     X Visual Studio is missing necessary components. Please re-run the Visual Studio  
>       installer for the "Desktop development with C++" workload, and include these    
>       components:
>         MSVC v142 - VS 2019 C++ x64/x86 build tools
>          - If there are multiple build tool versions available, install the latest    
>         C++ CMake tools for Windows
>         Windows 10 SDK
> [√] Android Studio (version 2024.1)
> [√] VS Code (version 1.92.2)
> [√] Connected device (4 available)
> [√] Network resources
> 
> ! Doctor found issues in 1 category.
> ```
> 
> Kindly look into this issue... Thanks in advance!

Hey, I couldn't reproduce your issue with the following commands:
```sh
flutter create flutter create in_app_review_repro_sep11
flutter build apk
flutter pub add in_app_review
flutter build apk
```

**Comment by rafidgotit** [comment]
> > I get the following error only when I try to build in release mode, debug mode just works fine.
> > ```
> > * What went wrong:
> > Execution failed for task ':in_app_review:verifyReleaseResources'.
> > > A build operation failed.
> >       Cannot parse result path string:                                
> >    > Cannot parse result path string:                                
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For more information, this is the output of my `flutter doctor`
> > ```
> > Doctor summary (to see all details, run flutter doctor -v):
> > [√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4037],
> >     locale en-US)
> > [√] Windows Version (Installed version of Windows is version 10 or higher)
> > [√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
> > [√] Chrome - develop for the web
> > [!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0)
> >     X Visual Studio is missing necessary components. Please re-run the Visual Studio  
> >       installer for the "Desktop development with C++" workload, and include these    
> >       components:
> >         MSVC v142 - VS 2019 C++ x64/x86 build tools
> >          - If there are multiple build tool versions available, install the latest    
> >         C++ CMake tools for Windows
> >         Windows 10 SDK
> > [√] Android Studio (version 2024.1)
> > [√] VS Code (version 1.92.2)
> > [√] Connected device (4 available)
> > [√] Network resources
> > 
> > ! Doctor found issues in 1 category.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Kindly look into this issue... Thanks in advance!
> 
> Hey, I couldn't reproduce your issue with the following commands:
> 
> ```shell
> flutter create flutter create in_app_review_repro_sep11
> flutter build apk
> flutter pub add in_app_review
> flutter build apk
> ```

could it be an issue related to corrupt gradle files?
I tried to build the same project on another device (MacBook) and the error didn't happen

**Comment by britannio** [comment]
> > > I get the following error only when I try to build in release mode, debug mode just works fine.
> > > ```
> > > * What went wrong:
> > > Execution failed for task ':in_app_review:verifyReleaseResources'.
> > > > A build operation failed.
> > >       Cannot parse result path string:                                
> > >    > Cannot parse result path string:                                
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For more information, this is the output of my `flutter doctor`
> > > ```
> > > Doctor summary (to see all details, run flutter doctor -v):
> > > [√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4037],
> > >     locale en-US)
> > > [√] Windows Version (Installed version of Windows is version 10 or higher)
> > > [√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
> > > [√] Chrome - develop for the web
> > > [!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0)
> > >     X Visual Studio is missing necessary components. Please re-run the Visual Studio  
> > >       installer for the "Desktop development with C++" workload, and include these    
> > >       components:
> > >         MSVC v142 - VS 2019 C++ x64/x86 build tools
> > >          - If there are multiple build tool versions available, install the latest    
> > >         C++ CMake tools for Windows
> > >         Windows 10 SDK
> > > [√] Android Studio (version 2024.1)
> > > [√] VS Code (version 1.92.2)
> > > [√] Connected device (4 available)
> > > [√] Network resources
> > > 
> > > ! Doctor found issues in 1 category.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Kindly look into this issue... Thanks in advance!
> > 
> > 
> > Hey, I couldn't reproduce your issue with the following commands:
> > ```shell
> > flutter create flutter create in_app_review_repro_sep11
> > flutter build apk
> > flutter pub add in_app_review
> > flutter build apk
> > ```
> 
> could it be an issue related to corrupt gradle files? I tried to build the same project on another device (MacBook) and the error didn't happen

Not sure. Did you have any luck with `flutter clean`?
