### ISSUE TITLE
Geeting error on creating a Release Apk 

### ISSUE THREAD

**Issue by gganger** [britannio/in_app_review#134]
`A problem was found with the configuration of task ':flutter_inappwebview_android:syncReleaseLibJars' (type 'LibraryAarJarsTask').
  - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.LibraryAarJarsTask' property 'javaResourcesJar' specifies file '/Users/builder/clone/build/flutter_inappwebview_android/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview_android.jar' which doesn't exist.`

**Comment by britannio** [comment]
Is your issue related to this package or the webview package?
