### ISSUE TITLE
Could frequent use of requestReview() lead to App Store penalties?

### ISSUE THREAD

**Issue by uayodev** [britannio/in_app_review#138]
Hi! Thanks for this great package!

I’ve been using requestReview() each time a user opens the app, which has helped generate a lot of positive reviews. My understanding was that await inAppReview.isAvailable() would return True only when the App Store deemed it appropriate, but I’ve noticed it always returns True, allowing requestReview() to be called every time.

Here’s the code:

final InAppReview inAppReview = InAppReview.instance;

if (await inAppReview.isAvailable()) {
    inAppReview.requestReview();
}

I’m now concerned that this frequent usage might trigger penalties or lower my app’s ranking. Is there a chance that Apple would penalize this kind of repeated use?

Thanks for any insights on this!

**Comment by britannio** [comment]
> This should not be used frequently as the underlying API's enforce strict quotas on this feature to provide a great user experience.

On iOS it will only appear three times in a 365-day period. It won't be penalised but it might annoy your users.
