### ISSUE TITLE
Submit button for Android disabled on Internal App Sharing

### ISSUE THREAD

**Issue by SmiffyKMc** [britannio/in_app_review#14]
Hey, just wanted to check real quick. I have the app review up and running and when trying to leave a review to test, I see the submit button is disabled? Is this something you have come across and if so do you have any instructions? Does it only become enabled for public reviews?

**Comment by SmiffyKMc** [comment]
I actually checked this up and it is indeed as expected. Maybe worth mentioning in your wiki.

[Internal App Sharing](https://developer.android.com/guide/playcore/in-app-review/test#internal-app-sharing)

**Comment by britannio** [comment]
@SmiffyKMc Does this help? https://github.com/britannio/in_app_review/commit/0925218065feed98c32f66a048b06e5f5297bf44

**Comment by SmiffyKMc** [comment]
Perfect! It'll help for other newcomers :) Great library btw
