### ISSUE TITLE
[Android] requestReview() works on Internal App Sharing, but not working after publish to Play Store.

### ISSUE THREAD

**Issue by FisherWL** [britannio/in_app_review#15]
```
  final InAppReview inAppReview = InAppReview.instance;

  void promptReview() async {
    if (await inAppReview.isAvailable()) {
      inAppReview.requestReview();
    } else {
      inAppReview.openStoreListing(appStoreId: '1515666116');
    }
  }
```
Identical code base.
tested on 2 android phones: ZTE blade A7 on android 9, Galaxy A71 on Android 10.

Internal App Sharing link:
[https://play.google.com/apps/test/RQRc_UnRrcU/ahAEJTaaTqODQmaAEYe8lWQ3z5P4kfxlxT5Pp5c2nJcvgqVWP0vOzTnbkbpBfSKzwn0h2s-muB8il3tnxyrjFf4DTp](https://play.google.com/apps/test/RQRc_UnRrcU/ahAEJTaaTqODQmaAEYe8lWQ3z5P4kfxlxT5Pp5c2nJcvgqVWP0vOzTnbkbpBfSKzwn0h2s-muB8il3tnxyrjFf4DTp)

Play Store link:
[https://play.google.com/store/apps/details?id=org.unitsconversion.unitconverter](https://play.google.com/store/apps/details?id=org.unitsconversion.unitconverter)

**Comment by britannio** [comment]
@FisherWL Can you confirm that you're following these guidelines?
> Since there is a quota on how many times the pop up can be shown, you should not trigger requestReview() via a button or other call-to-action option. Instead, you can reliably redirect users to your store listing via openStoreListing()

**Comment by FisherWL** [comment]
yes and no, there're 2 events trigger requestReview() in the app above:

 (1) a button (I'll change it to openStoreListing later);
 (2) the 1st time user goes back to the home page.

both of them work on internal sharing,
none of them work after downloading from Play store.

One of my testing phones is brand new, it never installed the app, (but it did share the same google account as the other phone).

Plus the guideline seems irrelevant to the topic because it doesn't explain the difference between internal sharing and published play store app.

**Comment by britannio** [comment]
> Plus the guideline seems irrelevant to the topic because it doesn't explain the difference between internal sharing and published play store app.

The behaviour is actually different by design, no quota is enforced when testing the app via internal app sharing which would explain why you are seeing the pop up when testing via internal app sharing but not via the production track.

**Comment by britannio** [comment]
@FisherWL Are you still having issues?

**Comment by FisherWL** [comment]
> @FisherWL Are you still having issues?

Thanks for asking, but I'm not sure, I'm still in the process of finding a working play store account and another andriod testing phone.

**Comment by britannio** [comment]
![image](https://user-images.githubusercontent.com/33752528/101396204-e0b98e80-38c2-11eb-9d2d-0349752d87ed.png)
> (2) the 1st time user goes back to the home page.

This is working.

**Comment by FisherWL** [comment]
> 
> 
> > (2) the 1st time user goes back to the home page.
> 
> This is working.

Thank you so much! Thanks for the great work and help!
