### ISSUE TITLE
How do I open the review in the play store

### ISSUE THREAD

**Issue by premtemp1** [britannio/in_app_review#31]
Hello,
  What is the key pair to open the review on the Android store.

here the description in the API  all --> inAppReview.openStoreListing(appStoreId: '...', microsoftStoreId: '...');

my appStoreId for apple and android are different

Thanks

**Comment by britannio** [comment]
As stated in the README:

`appStoreId` is only required on IOS and MacOS and can be found in App Store Connect under General > App Information > Apple ID.

`microsoftStoreId` is only required on Windows.

---
No id is required to open the Google Play Store.
