### ISSUE TITLE
how do i know i have reviewed on play store?

### ISSUE THREAD

**Issue by lequyhien98** [britannio/in_app_review#33]
hi, like title is there any way for me to know if i have reviewed?

**Comment by britannio** [comment]
Unfortunately not, the underlying API this plugin uses doesn't even confirm if the review pop up was displayed.

**Comment by lequyhien98** [comment]
thanks sir!

**Comment by kingdom96** [comment]
so what happens if user already rated the app? the pop up  is displayed again ?

**Comment by lequyhien98** [comment]
> Hello, thank you for the answer
> so what happens if user already rated the app? the pop up is displayed again ?

it still shows up

**Comment by britannio** [comment]
> Hello, thank you for the answer
> so what happens if user already rated the app? the pop up  is displayed again ? 

It will **not** reappear if the app has already been rated.
