### ISSUE TITLE
Prefilled Stars

### ISSUE THREAD

**Issue by AjinkyaTaranekar** [britannio/in_app_review#36]
Hello,

I am looking for a design, in which the user comes to the rating screen. There I show a rating bar, where if let says the number of stars is less than 4 then he is directed to contact us screen else in-app review prompt is shown to the user with stars already prefilled and he just needs to add a comment now (if any).

Is there any method to achieve this?

Thanks and Regards
Ajinkya Taranekar

**Comment by britannio** [comment]
There's no way to pre-fill stars in the review dialog.

**Comment by AjinkyaTaranekar** [comment]
Oh! I see.
