### ISSUE TITLE
Cannot get the system dialog to show

### ISSUE THREAD

**Issue by premtemp1** [britannio/in_app_review#37]
Hello,
  Thanks for plugin and sorry if you answered a similar question  before..

I install the plugin and added the logic

 final InAppReview inAppReview = InAppReview.instance;
  if (await inAppReview.isAvailable()) {
       inAppReview.requestReview();
   }

I hook up my Phone to my mac and ran it on my device from VSCode.  I see the popup dialog asking me to rate but the submit button is disable.  

However, if I build, deploy to TestFlight and  download to my device  then the nothing happens.. no dialog popup.

is this the normal behavior? If so, how can I get my QA to test it

Thanks for your help

**Comment by britannio** [comment]
Yes, it's expected behaviour as documented at https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview#discussion.

Maybe a video of it working locally + the aforementioned link will help your QA?
