### ISSUE TITLE
Allow to use custom Package IDs for Android 

### ISSUE THREAD

**Issue by nivisi** [britannio/in_app_review#39]
Hey! Thanks for this plugin.

In our app we have three type of builds: dev, stage and prod. For each of them we have different package names: `app.dev`, `app.stage` and just `app`.

Using this plugin it's not possible to test it: we have those prefixes for dev and stage builds, but the app is published w/o them.

Would be great if we had an option to pass the package ID to the plugin.

Thanks!

**Comment by britannio** [comment]
Assuming that my implementation of `openStoreListing()` works, wouldn't it be sufficient to test it once on a production build?

**Comment by nivisi** [comment]
@britannio sorry for a late response. Yep, that surely would make sense 😀
