### ISSUE TITLE
Dialog actions callback

### ISSUE THREAD

**Issue by preteambuy** [britannio/in_app_review#40]
Can we have a call back when the user interacts with the review dialog. This will help to determine if the user cancelled or dismissed the dialog so that we can effectively call it at a later point in time.

**Comment by britannio** [comment]
If the underlying API supported it then I'd love to implement such a feature however that's not the case.

**Comment by mayouf** [comment]
Hi @britannio ,

1st of all, thx for this plugins !

Are you sure, there is no way to catch the user's interaction with the dialog ???

It does not make because we should have the choice to send `inAppReview.requestReview()` OR our own customize dialog to send users to store page.
