### ISSUE TITLE
Non fatal issue detected with Crashlytics

### ISSUE THREAD

**Issue by fvisticot** [britannio/in_app_review#41]
I get this error on the firebase craslytics console:
This error occurs not very often.

PlatformException(no-scene, In-App Review could not find active scene, null, null)

Non-fatal Exception: FlutterError
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 597 (message_codecs.dart:597)
1  ???                            0x0 MethodChannel._invokeMethod + 158 (platform_channel.dart:158)

Version: 2.0.2

**Comment by fvisticot** [comment]
> I get this error on the firebase craslytics console:
> This error occurs not very often.
> 
> PlatformException(no-scene, In-App Review could not find active scene, null, null)
> 
> Non-fatal Exception: FlutterError
> 0 ??? 0x0 StandardMethodCodec.decodeEnvelope + 597 (message_codecs.dart:597)
> 1 ??? 0x0 MethodChannel._invokeMethod + 158 (platform_channel.dart:158)
> 
> Version: 2.0.2

Number of bugs regarding this issue is growing in crashlytics. Any idea to help me to fix this issue ?

**Comment by fvisticot** [comment]
I have this error for a lot  of my iOS Users (more than 150). Can you please help me to find a solution for iOS ?

**Comment by britannio** [comment]
I have fixed this issue in https://github.com/britannio/in_app_review/commit/048e8bd38a1edd3789c04771406ae7bb09384441. 
V2.0.3 will be released shortly with the fix!

**Comment by britannio** [comment]
V2.0.3 has been released!
