### ISSUE TITLE
Return Value for Reviews

### ISSUE THREAD

**Issue by AjinkyaTaranekar** [britannio/in_app_review#43]
Hello,

Can we get the return value (no of stars) in integer for the review submitted from requestReview() method?

Thanks & Regards

**Comment by britannio** [comment]
The underlying API doesn't provide such information unfortunately.

**Comment by mayouf** [comment]
Hi @britannio ,

1st of all, thx for this plugins !

Are you sure, there is no way to catch the user's interaction with the dialog ???

It does not make because we should have the choice to send `inAppReview.requestReview()` OR our own customize dialog to send users to store page.

**Comment by britannio** [comment]
@britannio Yep, it's unfortunate but it's an intentional decision by Apple and Google.
