### ISSUE TITLE
Execute _requestReview() after a while.

### ISSUE THREAD

**Issue by Gnaagounet** [britannio/in_app_review#45]
Hi,

I don't see how I can execute _requestReview() after a while, as plugin rate_my_app. How use settings, like minDays, minLaunches or   remindDays ?

**Comment by britannio** [comment]
Hey @Gnaagounet, this plugin doesn't handle such scenarios but you could use [shared_preferences](https://pub.dev/packages/shared_preferences) to track metrics like the number of app launches.

**Comment by Gnaagounet** [comment]
Hi @britannio , thanks for you reply, I'll check that ;)

**Comment by britannio** [comment]
Closing as a stale issue.
