### ISSUE TITLE
Is there a function to check if the user has given a review or not?

### ISSUE THREAD

**Issue by nikunjdk** [britannio/in_app_review#46]
I have an app that triggers the function after the user has completed a task. I was wondering if we can get to know if the user has already reviewed then I will not trigger the function.

**Comment by britannio** [comment]
There isn't such a function to do so. Although, if the app has already been reviewed then no pop up will appear when `requestReview()` is used so it won't cause any issues.

**Comment by nikunjdk** [comment]
Thanks!
