### ISSUE TITLE
 Does not open in my app

### ISSUE THREAD

**Issue by viniciusddrft** [britannio/in_app_review#47]
flutter version: 2.5.2
dart version: 2.14.3
plugin version: 2.0.3

It works perfectly when I installed it in shared mode, but in production it won't open even though it's the same code,

as it just didn't work in production i don't have logs :/

**Comment by britannio** [comment]
Are you testing on an Android device or an iOS device? They both have quotas that may be causing the behaviour you are describing.

https://developer.android.com/guide/playcore/in-app-review#quotas

**Comment by viniciusddrft** [comment]
I'm using on android,I will check what you said.


Thanks :)

**Comment by yashmittalJTG** [comment]
@britannio ???

**Comment by yashmittalJTG** [comment]
> +1

hey, deploy your app on internal app sharing, a link will be generated, use that link to download app, it will work fine.

**Comment by Vakil-Parth** [comment]
It does not work on production.

I have downloaded app from Playstore, but plugin does not show dialog.

**Comment by rickypid** [comment]
+1

**Comment by matszafraniec** [comment]
I have issue on Android too:
 
Plugin version: 2.0.3. 
Flutter 2.8.0.

Tested on Android 10 device distributed via Internal App Sharing. Completely fresh device, no quotas exceeded. Dialog doesn't show.

**Comment by britannio** [comment]
I just tested it on Android 11 via https://play.google.com/console/internal-app-sharing and it's still working flawlessly. Please read the [testing instructions](https://pub.dev/packages/in_app_review#testing) and [Android specific guidelines](https://developer.android.com/guide/playcore/in-app-review/test) in detail if there is still any confusion. I can't fix something that isn't broken.

**Comment by britannio** [comment]
Demo of it working https://photos.app.goo.gl/nYqyaQs5c9LZf22X6

**Comment by matszafraniec** [comment]
@britannio before I made publish in stores, I set Google Analytics event before I show app rating dialog. After 2 weeks after publish I can see it has been hit multiple times and I can observe satisfying numbers of new ratings on both: AppStore and PlayStore so it seems plugin is working fine :)

Thank you for support.

**Comment by britannio** [comment]
Closing this as a stale issue, drop a comment if there's still a problem and I'll reopen the issue.
