### ISSUE TITLE
System Review Popup is not being displayed.

### ISSUE THREAD

**Issue by shantiweb** [britannio/in_app_review#5]
System Review Pop up is not being displayed.
I have wrote following code inside  initState() function.

```
    WidgetsBinding.instance.addPostFrameCallback((_) async{
      if (await _inAppReview.isAvailable()) {
        print("WidgetsBinding Available");
        _inAppReview.requestReview();
      }
    });
```
Following is my debug log

```
I/PlayCore( 2860): UID: [10042]  PID: [2860] ReviewService : requestInAppReview (com.shantiwebsolution.bollywood_quiz)
I/PlayCore( 2860): UID: [10042]  PID: [2860] ReviewService : Initiate binding to the service.
I/PlayCore( 2860): UID: [10042]  PID: [2860] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore( 2860): UID: [10042]  PID: [2860] ReviewService : linkToDeath
I/PlayCore( 2860): UID: [10042]  PID: [2860] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/PlayCore( 2860): UID: [10042]  PID: [2860] ReviewService : Unbind from service.
I/flutter ( 2860): WidgetsBinding Available
I/Timeline( 2860): Timeline: Activity_launch_request id:com.shantiwebsolution.bollywood_quiz time:74560055
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : requestUpdateInfo(com.shantiwebsolution.bollywood_quiz)
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : Initiate binding to the service.
D/ViewRootImpl( 2860): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{2cc92c1 I.E...... R.....I. 0,0-0,0}
D/mali_winsys( 2860): new_window_surface returns 0x3000,  [1x1]-format:1
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
D/ViewRootImpl( 2860): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : linkToDeath
I/Timeline( 2860): Timeline: Activity_idle id: android.os.BinderProxy@f049bbc time:74560188
I/PlayCore( 2860): UID: [10042]  PID: [2860] OnRequestInstallCallback : onRequestInfo
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : Unbind from service.
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : requestUpdateInfo(com.shantiwebsolution.bollywood_quiz)
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : Initiate binding to the service.
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : linkToDeath
I/Timeline( 2860): Timeline: Activity_idle id: android.os.BinderProxy@3df8d69 time:74560426
D/ViewRootImpl( 2860): #3 mView = null
I/PlayCore( 2860): UID: [10042]  PID: [2860] OnRequestInstallCallback : onRequestInfo
I/PlayCore( 2860): UID: [10042]  PID: [2860] AppUpdateService : Unbind from service.
````

**Comment by britannio** [comment]
@shantiweb Can you confirm that you're following the testing instructions correctly? https://github.com/britannio/in_app_review#android-1

**Comment by chris-rutkowski** [comment]
I have exactly the same issue.

```
            if (await inAppReview.isAvailable()) {
              await inAppReview.requestReview();
            } else {
              await inAppReview.openStoreListing(appStoreId: '1526425219');
            }
```

I managed to see the popup maybe once, but that's all. You can see exactly above code in action if you download my app https://well-spoken.app . I came up with some lame walkaround (you can see it when you download my app), but it's not the ideal solution.

**Comment by britannio** [comment]
@chris-rutkowski 
![image](https://user-images.githubusercontent.com/33752528/91564414-83638800-e938-11ea-8cba-5da98ffd8cd1.png)
I certainly didn't make this clear enough when I first released this plugin but the system API's are not designed to be used in this way. On Android, after the first attempt at showing the pop-up, there's no guarantee that it will be shown again and this is an intentional limitation likely to prevent spam or misuse. 
https://developer.android.com/guide/playcore/in-app-review#quotas

Please follow the guidelines as stated here: https://developer.android.com/guide/playcore/in-app-review#when-to-request

Also, I'm loving the app UX!

**Comment by britannio** [comment]
As a side note, this quota is not enforced when running the app via internal app sharing or internal testing provided by the Google Play Store as stated here: https://developer.android.com/guide/playcore/in-app-review/test#test-play-store

**Comment by chris-rutkowski** [comment]
Thanks for compliment. 
So our code is correct, but Google and Apple is throating it, that's understandable. Is there any callback possible to understand what happens on the screen?
I tried to wrap code in try catch but to no avail.

**Comment by britannio** [comment]
> Thanks for compliment.
> So our code is correct, but Google and Apple is throating it, that's understandable. Is there any callback possible to understand what happens on the screen?
> I tried to wrap code in try catch but to no avail.

@chris-rutkowski 
Unfortunately not, the Google and Apple API don't let us know if the pop up was shown hence making it unsuitable for a permanent button. You can use the following code for your 'Rate us in the Play Store' button:
`await inAppReview.openStoreListing(appStoreId: '1526425219');`

For your app, you could use the following code after a certain number of words have been learnt?
```dart
if (await inAppReview.isAvailable()) {
  await inAppReview.requestReview()
}
```

**Comment by britannio** [comment]
@shantiweb I haven't received a response from you so I'm closing this issue.

**Comment by shantiweb** [comment]
Sorry, I was sick for last week.
This works perfectly.

Only thing is we can not test in development.
But can test in beta tests .
