### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50.

### ISSUE THREAD

**Issue by SlavisDEV** [britannio/in_app_review#50]
I try to build Android app, but I got following error:
`A problem occurred configuring project ':in_app_review'.
> Could not resolve all artifacts for configuration ':in_app_review:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50.
     Required by:
         project :in_app_review > com.android.tools.build:gradle:3.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.lint:lint-gradle-api:26.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:gradle-api:3.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > androidx.databinding:databinding-compiler-common:3.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:common:26.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.build:manifest-merger:26.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools.analytics-library:tracker:26.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4
         project :in_app_review > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdk-common:26.5.4 > com.android.tools.analytics-library:shared:26.5.4
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.50/kotlin-stdlib-jdk8-1.3.50.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.50/kotlin-stdlib-jdk8-1.3.50.pom'.
               > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed`

Anyone knows what is wrong?

**Comment by EArminjon** [comment]
use kotlin 1.6.10 : 
```
  ext.kotlin_version = '1.6.10'
```

**Comment by britannio** [comment]
Closing as a stale issue. If you're still facing this issue, drop a comment and I'll reopen the issue.
