### ISSUE TITLE
What happens if the user had already left a review?

### ISSUE THREAD

**Issue by mirrorlink** [britannio/in_app_review#55]
Does the modal open? Or it doesnt? is there a way to know that so its not annoying to ask all the time of if the user uninstalls and reinstalls the app?

Could the requestReview return a boolean so we know the review modal was or not indeed opened?

**Comment by britannio** [comment]
The modal does not open however the underlying API does not expose this information beforehand. This means that a boolean cannot be returned.

**Comment by mirrorlink** [comment]
> Can this perhaps be checked in the .isAvailable()? Otherwise it seems to the user that the button just doesn't work. Or what is the best thing you can do in this case?

JobMoll this should not be put in a button. Its by design. If you want to put in a button you have to call a different method, openStoreListing()
