### ISSUE TITLE
What happens if the user had already left a review?

### ISSUE THREAD

**Issue by hashirshoaeb** [britannio/in_app_review#57]
Asking this question in reference to #55. 

Does `.isAvailable()` checks this information?

**Comment by nikb7** [comment]
Afaik, it doesn't
I had tested this for my app and it doesn't check if the user has left a review or not.

**Comment by britannio** [comment]
> Asking this question in reference to #55.
> 
> Does `.isAvailable()` checks this information?

No, the underlying API does not expose this information so `isAvailable()` cannot return `false` after a review was left.

**Comment by sanyakuznezov** [comment]
is there a callback implementation when one of the buttons in the dialog is clicked. And how do you know if a user left a review?

**Comment by britannio** [comment]
> is there a callback implementation when one of the buttons in the dialog is clicked. And how do you know if a user left a review?

There is no such callback, the API does not provide such information.
