### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by ferraridamiano** [britannio/in_app_review#6]
When you compile an app with this package it shows:

```
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_review-0.2.0+3\android\src\main\java\dev\britannio\in_app_review\InAppReviewPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

It is not an error, just a warning, is it possible to fix this?

**Comment by britannio** [comment]
It's just a warning and shouldn't affect the functionality of the plugin. See https://github.com/flutter/flutter/issues/37616#issuecomment-615007073

**Comment by britannio** [comment]
On that note, I've fixed the warning in https://github.com/britannio/in_app_review/commit/90a936f5d2a49421eb31c2e898d25edef032a90f

**Comment by britannio** [comment]
@ferraridamiano And it's been published https://pub.dev/packages/in_app_review/versions/0.2.0+4
