### ISSUE TITLE
Nothing happens on macOS

### ISSUE THREAD

**Issue by mgenware** [britannio/in_app_review#60]
```dart
if (await inAppReview.isAvailable()) {
  await inAppReview.requestReview();
}
```

I can confirm `requestReview` is called in debug mode, but nothing happens on macOS, nor are there any relevant logs seen. Is that normal?

<details>
 <summary>flutter doctor</summary>
<pre>
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.67.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
</pre>
</details>

**Comment by mgenware** [comment]
Tried calling the native `requestReview` through method channel, got the same result. Guess it's a macOS issue.

**Comment by britannio** [comment]
> Tried calling the native `requestReview` through method channel, got the same result. Guess it's a macOS issue.

Hey, this should work on MacOS, did it work in the end?

**Comment by mgenware** [comment]
Not sure what went wrong, never worked on my side, even on a native app created from xcode. I guess it only works on app store builds? Will update this thread when my app gets approved.

**Comment by mgenware** [comment]
It works on app store.
