### ISSUE TITLE
Way to find if review popup will not open

### ISSUE THREAD

**Issue by nigamsiddhant** [britannio/in_app_review#63]
Hello,

I want to show in app rating when it is Available but mostly inAppReview.isAvailable() is giving true and then i am trying to open inAppReview.requestReview(); but due to some reason it is not getting opened, 

Is there a way to get inAppReview.isAvailable as. also or suppose inAppReview.requestReview fails to open so it return false so that I can take the user to App Store or play store.

**Comment by paul678** [comment]
Unfortunately there would be no way know for sure if the In-App UI was ever shown or not (e.g android [docs](https://developer.android.com/guide/playcore/in-app-review/kotlin-java#launch-review-flow)). 

You will need to design your flow as to account for this and unfortunately you won't be able to implement the "redirect to store if in-app is not available".

**Comment by britannio** [comment]
Yes, you can rely on it opening once per user, after that, you can use `openStoreListing()`.
