### ISSUE TITLE
ios production app not work

### ISSUE THREAD

**Issue by huangxin813** [britannio/in_app_review#64]
Flutter : Channel stable, 2.10.3
in_app_review: ^2.0.4
platform: iOS 15.5
it works on debug mode, but when i install the production app from AppStore,  nothing happen.

```
 InAppReview inAppReview = InAppReview.instance;
 if (await inAppReview.isAvailable()) {
      inAppReview.requestReview();
 }
```

**Comment by leifhacks** [comment]
Same for me! Also does not work when installing via Test Flight.

Flutter : Channel stable, 3.0.5
in_app_review: ^2.0.4
platform: iOS 15.4.1

**Comment by huangxin813** [comment]
Maybe i found the reason. There is an InAppReview switcher in Settings -> AppStore, after enable it, the InAppReview dialog can popup, but only once, maybe it's apple's policy.

**Comment by britannio** [comment]
> Maybe i found the reason. There is an InAppReview switcher in Settings -> AppStore, after enable it, the InAppReview dialog can popup, but only once, maybe it's apple's policy.

It is indeed Apple policy, you can read more here: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/3566727-requestreview#discussion

> Please close the bug.

Sure.

**Comment by ziqq** [comment]
> https://developer.apple.com/documentation/storekit/skstorereviewcontroller/3566727-requestreview#discussion

Yes it is. I have the same problem. Does anyone know how to fix this without going to the AppStore settings?
