### ISSUE TITLE
openStoreListing() on iOS is broken

### ISSUE THREAD

**Issue by alexandermcpherson** [britannio/in_app_review#67]
Calling this function via a button opens safari on iOS with an invalid address. 
The url is correct `apps.apple.com/app/id1096827640?action=w` because I can open it in safari on my mac but in iOS Safari it doesnt open a valid url.
I am setting the id correctly also with `String _appStoreId = '1096827640';`

**Comment by britannio** [comment]
@alexandermcpherson Are you testing this via the iOS simulator?

**Comment by britannio** [comment]
Closing as a stale issue. Reply and I'll reopen it.
