### ISSUE TITLE
Execution failed for task ':in_app_review:parseDebugLocalResources'

### ISSUE THREAD

**Issue by talhameer** [britannio/in_app_review#77]
I get the following error when I run the app after adding the package... Please guide me on how to fix it...

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':in_app_review:parseDebugLocalResources'.
> Could not resolve all files for configuration ':in_app_review:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: C:\Users\DELL\AppData\Local\Android\Sdk\platforms\android-29\android.jar.
         > zip END header not found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib\main.dart:1
`

**Comment by britannio** [comment]
Please could you update the package and let me know if this issue still occurs? Thanks.

**Comment by talhameer** [comment]
I removed the SDK 29 from the android studio and then started the project. Now it's working perfectly fine. Thanks
