### ISSUE TITLE
Android when done reviewed, press RequestReview again not show popup Review again it quiet.

### ISSUE THREAD

**Issue by khmergeo** [britannio/in_app_review#8]
Hello sir, Can we know our reviewed rating is already or not?
I got nothing to happen when I already rated. And I want to show the user he is already rated or show popup Review dialog again.

This is my code.

```
Future<void> _requestReview() async {
    if (await _inAppReview.isAvailable()) {
      await _inAppReview.requestReview();
    } else {
      await _inAppReview.openStoreListing(appStoreId: _appStoreId);
    }
  }
```

**Comment by britannio** [comment]
See https://github.com/britannio/in_app_review/issues/5#issuecomment-682559674. 
The Play Store and App Store enforce a quota on how many times the popup can be shown and they don't provide us with any information such as if the popup was shown or if the user has already rated the app. This is a limitation of the provided APIs hence there isn't anything I can do.

https://developer.android.com/guide/playcore/in-app-review#quotas
