### ISSUE TITLE
[Warning] Uses or overrides a deprecated API on Android.

### ISSUE THREAD

**Issue by vqthanh1412489** [britannio/in_app_review#84]
## 🐛 Bug Report

`.pub-cache/hosted/pub.dartlang.org/in_app_review-2.0.6/android/src/main/java/dev/britannio/in_app_review/InAppReviewPlugin.java uses or overrides a deprecated API.`

### Expected behavior
This warning does not show

### Reproduction steps
Run the project as usual and you can see this warning.

### Configuration

**Version:**
^2.0.6

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by under3415** [comment]
This may be related: https://stackoverflow.com/questions/63953891/requestreview-was-deprecated-in-ios-14-0
Any word on the fix for this?
