### ISSUE TITLE
Need getInstance method

### ISSUE THREAD

**Issue by ziqq** [britannio/in_app_review#88]
Need getInstance method for injectable resolveUsing

**Comment by ziqq** [comment]
> Hey, could you clarify the issue you're having?
> 
> Does this help? https://pub.dev/documentation/in_app_review/latest/in_app_review/InAppReview/instance.html

<img width="550" alt="image" src="https://user-images.githubusercontent.com/20646071/233348995-dbb71338-4d7b-4e0e-a4cc-1ff4b26b39b0.png">

**Comment by britannio** [comment]
> > Hey, could you clarify the issue you're having?
> > Does this help? https://pub.dev/documentation/in_app_review/latest/in_app_review/InAppReview/instance.html
> 
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/20646071/233348995-dbb71338-4d7b-4e0e-a4cc-1ff4b26b39b0.png">

```dart
resolveUsing: () => InAppReview.instance
```

Does this work? Seems like it expects a function rather than the InAppReview object.

**Comment by ziqq** [comment]
> Does this work? Seems like it expects a function rather than the InAppReview object.

No its not working

<img width="550" alt="image" src="https://user-images.githubusercontent.com/20646071/233553237-28f5a4de-4066-4a9c-9d6a-923105bfaa11.png">
