### ISSUE TITLE
Also write a review after star popup

### ISSUE THREAD

**Issue by TiaanvdRiel** [britannio/in_app_review#90]
Does calling inAppReview.requestReview() aslso ask the user to write a review after they've left a star rating? My client wants this functionality, similar to the app below, but I can't get past the first star review popup in any testing environment, and I can't launch this to production just to test

https://github.com/britannio/in_app_review/assets/75138455/66a38714-88f6-4dbd-a1f7-4208b1edb508

**Comment by britannio** [comment]
The main popup will not do this but opening the store listing will show a popup with a review section.

**Comment by TiaanvdRiel** [comment]
Thank you for the reply, is there a way to open the review section like they are from a modal? I have no idea how they are achieving that effect then.

**Comment by TiaanvdRiel** [comment]
Also, so this basically means that choosing to use inAppReview.requestReview() means that you are sacrificing any written reviews and limiting yourself to only ratings?

**Comment by britannio** [comment]
> Thank you for the reply, is there a way to open the review section like they are from a modal? I have no idea how they are achieving that effect then.

`openStoreListing()` should work.
