### ISSUE TITLE
Cannot rate app at the second time.

### ISSUE THREAD

**Issue by lamlengend98** [britannio/in_app_review#91]
On IOS, I call ```requestReview()``` at the first, it shows the modal and I do rating worked
But after that, I call ```requestReview()``` at the second, nothing response, nothing show
How can I know what happen because I cannot debug this?

**Comment by lamlengend98** [comment]
@britannio

**Comment by britannio** [comment]
Here's what ChatGPT thinks to save you some time in future: https://chat.openai.com/share/78f1d49b-2b20-4b92-814d-7149b6c39f22
