### ISSUE TITLE
IOS action submit don't work 

### ISSUE THREAD

**Issue by nguyenquynh201** [britannio/in_app_review#98]
I can't press submit button when calling requestReview
![IMG_4C5329F54D2F-1](https://github.com/britannio/in_app_review/assets/80728170/475857a2-1f4e-4d4b-b3c0-d2b1bb9af28f)

**Comment by apackin** [comment]
Are you seeing that on production? The docs say it is disabled while testing:
`
Real reviews cannot be created while testing requestReview() and the submit button is disabled to emphasize this.
`
